name: podcharts-backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - fastapi>=0.115.0
    - uvicorn[standard]>=0.30.0
    - python-dotenv>=1.0.1
    - psycopg[binary]>=3.2.1
    - psycopg-pool>=3.2.1
    - redis>=5.0.8
    - httpx>=0.27.2

